l_english:
 CK3DISPLAYNAME: "Crusader Kings III to Europa Universalis IV"
 CK3GAME: "Crusader Kings III"
 EU4GAME: "Europa Universalis IV"
 CK3FOLDER: "Crusader Kings III Install Directory"
 CK3FOLDERTIP: "The path on your computer where Crusader Kings III is installed"
 CK3MOD: "Crusader Kings III Mod Directory"
 CK3MODTIP: "The path on your computer where Crusader Kings III stores mods"
 EU4FOLDER: "Europa Universalis IV Install Directory"
 EU4FOLDERTIP: "The path on your computer where Europa Universalis IV is installed"
 CK3FILE: "Path to the converter executable"
 CK3FILETIP: "Path to CK3ToEU4Converter.exe"
 CK3SAVE: "Path to the CK3 savegame"
 CK3SAVETIP: "Path to your savegame from CK3"
 CK3DOC: "Crusader Kings III Documents Directory"
 CK3DOCTIP: "A path on your computer where Crusader Kings III keeps temporary files"
 EU4MOD: "Europa Universalis IV Mod Directory"
 EU4MODTIP: "The path on your computer where Europa Universalis IV stores mods"

