l_latin:
 CK3DISPLAYNAME: "ex Crusader Kings III ad Europam Universalem IV"
 CK3GAME: "Crusader Kings III"
 EU4GAME: "Europa Universalis IV"
 CK3FOLDER: "Scapus locationis Crusader Kings III"
 CK3FOLDERTIP: "Via in qua locatus est ludus Crusader Kings III"
 CK3MOD: "Scapus correctionum Crusader Kings III"
 CK3MODTIP: "Via in qua locatae sunt correctiones Crusader Kings III"
 EU4FOLDER: "Scapus locationis Europae Universalis IV"
 EU4FOLDERTIP: "Via in qua locatus est ludus Europa Universalis IV"
 CK3FILE: "Via programmatis"
 CK3FILETIP: "Via ad CK3ToEU4Converter.exe"
 CK3SAVE: "Via ad conditum CK3"
 CK3SAVETIP: "Via ad conditum CK3"
 CK3DOC: "Scapus documentorum Crusader Kings III"
 CK3DOCTIP: "Via in qua Europa Crusader Kings III scribit fasciculos temporales"
 EU4MOD: "Scapus correctionum Europa Universalis IV"
 EU4MODTIP: "Via in qua locatae sunt correctiones Europa Universalis IV"

