l_french:
 CK3DISPLAYNAME: "de Crusader Kings III à Europa Universalis IV"
 CK3GAME: "Crusader Kings III"
 EU4GAME: "Europa Universalis IV"
 CK3FOLDER: "Répertoire d'installation de Crusader Kings III"
 CK3FOLDERTIP: "Le chemin sur votre ordinateur où Crusader Kings III est installé"
 CK3MOD: "Répertoire des mods Crusader Kings III"
 CK3MODTIP: "Le chemin sur votre ordinateur où Crusader Kings III stocke les mods"
 EU4FOLDER: "Répertoire d'installation d'Europa Universalis IV"
 EU4FOLDERTIP: "Le chemin sur votre ordinateur où Europa Universalis IV est installé"
 CK3FILE: "Chemin vers l'exécutable du convertisseur"
 CK3FILETIP: "Chemin vers CK3ToEU4Converter.exe"
 CK3SAVE: "Chemin vers la sauvegarde CK3"
 CK3SAVETIP: "Chemin vers votre sauvegarde de CK3"
 CK3DOC: "Répertoire des documents Crusader Kings III"
 CK3DOCTIP: "Un chemin sur votre ordinateur où Crusader Kings III conserve des fichiers temporaires"
 EU4MOD: "Répertoire des mods Europa Universalis IV"
 EU4MODTIP: "Le chemin sur votre ordinateur où Europa Universalis IV stocke les mods"

